/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GaleriaIdRouteImport } from './routes/galeria.$id'
import { Route as GaleriaKategoriaCategoryRouteImport } from './routes/galeria.kategoria.$category'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaIdRoute = GaleriaIdRouteImport.update({
  id: '/galeria/$id',
  path: '/galeria/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaKategoriaCategoryRoute =
  GaleriaKategoriaCategoryRouteImport.update({
    id: '/galeria/kategoria/$category',
    path: '/galeria/kategoria/$category',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/galeria/$id': typeof GaleriaIdRoute
  '/galeria/kategoria/$category': typeof GaleriaKategoriaCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/galeria/$id': typeof GaleriaIdRoute
  '/galeria/kategoria/$category': typeof GaleriaKategoriaCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/galeria/$id': typeof GaleriaIdRoute
  '/galeria/kategoria/$category': typeof GaleriaKategoriaCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/sitemap.xml' | '/galeria/$id' | '/galeria/kategoria/$category'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/galeria/$id' | '/galeria/kategoria/$category'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/galeria/$id'
    | '/galeria/kategoria/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GaleriaIdRoute: typeof GaleriaIdRoute
  GaleriaKategoriaCategoryRoute: typeof GaleriaKategoriaCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria/$id': {
      id: '/galeria/$id'
      path: '/galeria/$id'
      fullPath: '/galeria/$id'
      preLoaderRoute: typeof GaleriaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria/kategoria/$category': {
      id: '/galeria/kategoria/$category'
      path: '/galeria/kategoria/$category'
      fullPath: '/galeria/kategoria/$category'
      preLoaderRoute: typeof GaleriaKategoriaCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GaleriaIdRoute: GaleriaIdRoute,
  GaleriaKategoriaCategoryRoute: GaleriaKategoriaCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
